// lib/docgenDrive.js — the "source of truth" Drive mirror for the Document Number Generator.
// Firestore is the realtime database; after each generate (and on demand) we rebuild ONE CSV
// from every record and overwrite the same Drive file, so there is always a single spreadsheet
// in the Drive folder that stays aligned with the in-app Database tab.
//
// We reuse the reviewer-identity drive.file OAuth flow already in lib/auth.js — no service
// account (org policy blocks those). The file id is remembered in Firestore (docgen_meta/drive)
// so every write targets the same file rather than creating duplicates.

const CSV_MIME = "text/csv";
export const MIRROR_FILENAME = "Document Number Register (source of truth).csv";

// Stable column order for the spreadsheet.
const COLUMNS = [
  ["number", "Document Number"],
  ["date", "Date of Input"],
  ["pic", "PIC"],
  ["jira", "JIRA Number"],
  ["department", "Business Unit"],
  ["docType", "Document Type"],
  ["category", "Document Category"],
  ["value", "Document Value"],
  ["title", "Document Title"],
  ["entity", "Pluang Entity"],
  ["counterparty", "Counterparty Name"],
  ["approvers", "Business Approvers"],
  ["signingMethod", "Signing Method"],
  ["folderCode", "Folder Code"],
  ["series", "Series"],
  ["year", "Year"],
  ["authorEmail", "Generated By"],
];

const esc = (v) => {
  const s = v == null ? "" : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

// Build the CSV from the live record list. Sorted by year then sequence (sheet-natural order).
export function buildRegisterCsv(records) {
  const rows = [...records].sort((a, b) => (a.year - b.year) || (a.seq - b.seq));
  const header = COLUMNS.map(([, label]) => esc(label)).join(",");
  const body = rows.map((r) => COLUMNS.map(([key]) => esc(r[key])).join(",")).join("\n");
  return header + "\n" + body + "\n";
}

const CREATE_URL =
  "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&fields=id,name,webViewLink";
const updateUrl = (id) =>
  `https://www.googleapis.com/upload/drive/v3/files/${id}?uploadType=media&supportsAllDrives=true&fields=id,name,webViewLink`;

async function createFile(blob, accessToken, folderId) {
  const metadata = { name: MIRROR_FILENAME, mimeType: CSV_MIME, parents: folderId ? [folderId] : undefined };
  const form = new FormData();
  form.append("metadata", new Blob([JSON.stringify(metadata)], { type: "application/json" }));
  form.append("file", blob, MIRROR_FILENAME);
  const res = await fetch(CREATE_URL, { method: "POST", headers: { Authorization: `Bearer ${accessToken}` }, body: form });
  const out = await res.json().catch(() => ({}));
  if (!res.ok) { const e = new Error(out?.error?.message || `Drive create failed (${res.status}).`); e.status = res.status; throw e; }
  return out;
}

async function updateFile(fileId, blob, accessToken) {
  const res = await fetch(updateUrl(fileId), {
    method: "PATCH",
    headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": CSV_MIME },
    body: blob,
  });
  const out = await res.json().catch(() => ({}));
  if (!res.ok) { const e = new Error(out?.error?.message || `Drive update failed (${res.status}).`); e.status = res.status; throw e; }
  return out;
}

// Overwrite (or create) the single register file. Returns { file, fileId } so the caller can
// persist the id. If the remembered id 404s (file deleted/moved), we create a fresh one.
export async function mirrorRegisterToDrive(records, { accessToken, folderId, fileId }) {
  const blob = new Blob([buildRegisterCsv(records)], { type: CSV_MIME });
  if (fileId) {
    try {
      const file = await updateFile(fileId, blob, accessToken);
      return { file, fileId: file.id };
    } catch (e) {
      if (e.status !== 404) throw e; // 404 → fall through and recreate
    }
  }
  const file = await createFile(blob, accessToken, folderId);
  return { file, fileId: file.id };
}

// Local download fallback (used when Drive sync is disabled, or for an ad-hoc copy).
export function downloadRegisterCsv(records) {
  const blob = new Blob([buildRegisterCsv(records)], { type: CSV_MIME });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = MIRROR_FILENAME;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
