// lib/docgenDrive.js — the "source of truth" Drive mirror for the Document Number Generator.
// Firestore is the realtime database; after each generate (and on demand) we rebuild the full
// register and overwrite a single NATIVE GOOGLE SHEET in the Drive folder, so there is always
// one spreadsheet — opening directly in Google Sheets — that stays aligned with the in-app
// Database tab.
//
// We send CSV bytes but ask Drive to convert them to a Google Sheet (target mimeType
// application/vnd.google-apps.spreadsheet). This needs no Sheets API and no extra scope — it
// works with the existing reviewer-identity drive.file OAuth flow in lib/auth.js (no service
// account; org policy blocks those). The file id is remembered in Firestore (docgen_meta/drive)
// so every write targets the same Sheet rather than creating duplicates.

const CSV_MIME = "text/csv";
const SHEET_MIME = "application/vnd.google-apps.spreadsheet"; // native Google Sheet
// No file extension — it's a Google Sheet, not a .csv on disk.
export const MIRROR_FILENAME = "Document Number Register (source of truth)";

// Stable column order for the spreadsheet.
const COLUMNS = [
  ["number", "Document Number"],
  ["date", "Date of Input"],
  ["pic", "PIC"],
  ["jira", "JIRA Number"],
  ["department", "Business Unit"],
  ["docType", "Document Type"],
  ["category", "Document Category"],
  ["value", "Document Value"],
  ["title", "Document Title"],
  ["entity", "Pluang Entity"],
  ["counterparty", "Counterparty Name"],
  ["valueCurrency", "Currency"],
  ["valueAmount", "Amount"],
  ["valueFrequency", "Frequency"],
  ["usdEquivalent", "USD Value (per annum / one-time)"],
  ["approvers", "Business Approvers"],
  ["signingMethod", "Signing Method"],
  ["folderCode", "Folder Code"],
  ["series", "Series"],
  ["year", "Year"],
  ["authorEmail", "Generated By"],
];

const esc = (v) => {
  const s = v == null ? "" : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

// Build the CSV from the live record list. Sorted by year then sequence (sheet-natural order).
export function buildRegisterCsv(records) {
  const rows = [...records].sort((a, b) => (a.year - b.year) || (a.seq - b.seq));
  const header = COLUMNS.map(([, label]) => esc(label)).join(",");
  const body = rows.map((r) => COLUMNS.map(([key]) => esc(r[key])).join(",")).join("\n");
  return header + "\n" + body + "\n";
}

// A cheap content fingerprint of the register, used by the live sync to skip redundant writes
// (and to coordinate across browser sessions via docgen_meta). Changes whenever the Sheet's
// content would change. FNV-1a over the rendered CSV + the row count.
export function registerSignature(records) {
  const csv = buildRegisterCsv(records);
  let h = 0x811c9dc5;
  for (let i = 0; i < csv.length; i++) { h ^= csv.charCodeAt(i); h = Math.imul(h, 0x01000193); }
  return `${(h >>> 0).toString(36)}:${records.length}`;
}

const CREATE_URL =
  "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&supportsAllDrives=true&fields=id,name,webViewLink";
const updateUrl = (id) =>
  `https://www.googleapis.com/upload/drive/v3/files/${id}?uploadType=media&supportsAllDrives=true&fields=id,name,webViewLink`;

async function createFile(blob, accessToken, folderId) {
  // Target mimeType = Google Sheet → Drive converts the uploaded CSV media into a native Sheet.
  const metadata = { name: MIRROR_FILENAME, mimeType: SHEET_MIME, parents: folderId ? [folderId] : undefined };
  const form = new FormData();
  form.append("metadata", new Blob([JSON.stringify(metadata)], { type: "application/json" }));
  form.append("file", blob, MIRROR_FILENAME); // media is text/csv; Drive converts on import
  const res = await fetch(CREATE_URL, { method: "POST", headers: { Authorization: `Bearer ${accessToken}` }, body: form });
  const out = await res.json().catch(() => ({}));
  if (!res.ok) { const e = new Error(out?.error?.message || `Drive create failed (${res.status}).`); e.status = res.status; throw e; }
  return out;
}

async function updateFile(fileId, blob, accessToken) {
  // Replacing a Google Sheet's content: upload CSV media and Drive re-converts it into the Sheet,
  // keeping the same file id (and URL). Content-Type tells Drive the media is CSV.
  const res = await fetch(updateUrl(fileId), {
    method: "PATCH",
    headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": CSV_MIME },
    body: blob,
  });
  const out = await res.json().catch(() => ({}));
  if (!res.ok) { const e = new Error(out?.error?.message || `Drive update failed (${res.status}).`); e.status = res.status; throw e; }
  return out;
}

// Overwrite (or create) the single register file. Returns { file, fileId } so the caller can
// persist the id. If the remembered id 404s (file deleted/moved), we create a fresh one.
export async function mirrorRegisterToDrive(records, { accessToken, folderId, fileId }) {
  const blob = new Blob([buildRegisterCsv(records)], { type: CSV_MIME });
  if (fileId) {
    try {
      const file = await updateFile(fileId, blob, accessToken);
      return { file, fileId: file.id };
    } catch (e) {
      if (e.status !== 404) throw e; // 404 → fall through and recreate
    }
  }
  const file = await createFile(blob, accessToken, folderId);
  return { file, fileId: file.id };
}

// Local download fallback (used when Drive sync is disabled, or for an ad-hoc copy).
export function downloadRegisterCsv(records) {
  const blob = new Blob([buildRegisterCsv(records)], { type: CSV_MIME });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = MIRROR_FILENAME;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
